# Generated by Django 6.1 on 2026-09-01 23:17

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LlaveroNFC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único no predecible grabado en la memoria del chip NFC.', primary_key=True, serialize=False, unique=True)),
                ('nombre_menor', models.CharField(help_text='Ej: Lucas', max_length=60, verbose_name='Nombre del niño/a')),
                ('apellidos_menor', models.CharField(help_text='Ej: Martínez Gómez', max_length=100, verbose_name='Apellidos del niño/a')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('foto', models.ImageField(blank=True, help_text='Foto clara del rostro para identificación rápida en caso de pérdida.', null=True, upload_to='llaveros/avatares/', verbose_name='Foto / Avatar reciente')),
                ('nombre_contacto_1', models.CharField(help_text='Ej: Mamá (Laura Gómez)', max_length=80, verbose_name='Nombre Contacto Principal')),
                ('parentesco_contacto_1', models.CharField(default='Madre', max_length=40, verbose_name='Parentesco Contacto 1')),
                ('telefono_contacto_1', models.CharField(help_text='Número al que llamará el botón principal de emergencia.', max_length=20, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener formato internacional válido (ej: +34612345678 o 612345678).', regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono SOS Principal')),
                ('nombre_contacto_2', models.CharField(blank=True, help_text='Ej: Papá (Carlos Martínez) o Abuelos', max_length=80, null=True, verbose_name='Nombre Contacto Secundario')),
                ('parentesco_contacto_2', models.CharField(blank=True, max_length=40, null=True, verbose_name='Parentesco Contacto 2')),
                ('telefono_contacto_2', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener formato internacional válido (ej: +34612345678 o 612345678).', regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono SOS Secundario')),
                ('grupo_sanguineo', models.CharField(choices=[('A+', 'A Positivo (A+)'), ('A-', 'A Negativo (A-)'), ('B+', 'B Positivo (B+)'), ('B-', 'B Negativo (B-)'), ('AB+', 'AB Positivo (AB+)'), ('AB-', 'AB Negativo (AB-)'), ('O+', 'O Positivo (O+)'), ('O-', 'O Negativo (O-)'), ('DESC', 'Desconocido / No especificado')], default='DESC', max_length=5, verbose_name='Grupo Sanguíneo')),
                ('alergias_graves', models.TextField(blank=True, help_text='Alergias a alimentos, medicamentos, picaduras (ej: Cacahuetes, Penicilina, Látex).', verbose_name='Alergias Críticas')),
                ('enfermedades_condiciones', models.TextField(blank=True, help_text='Ej: Asma, Diabetes Tipo 1, Epilepsia, Autismo / TEA (no verbal).', verbose_name='Condiciones Médicas')),
                ('medicacion_urgencia', models.CharField(blank=True, help_text='Ej: Lleva Autoinyector de Adrenalina (Epipen) en el bolsillo lateral de la mochila.', max_length=255, verbose_name='Medicación de Urgencia / Ubicación')),
                ('observaciones_medicas', models.TextField(blank=True, help_text='Cualquier indicación crucial para los sanitarios o quien encuentre al menor.', verbose_name='Instrucciones Adicionales')),
                ('codigo_chip_fisico', models.CharField(blank=True, help_text='Identificador de fábrica del chip NTAG213/215/216 (opcional para control de stock).', max_length=50, null=True, verbose_name='UID del Chip NFC Físico')),
                ('esta_activo', models.BooleanField(default=True, help_text='Si se desactiva, la ficha pública mostrará un aviso de llavero inhabilitado.', verbose_name='Llavero Activo')),
                ('contador_escaneos', models.PositiveIntegerField(default=0, verbose_name='Total de Escaneos NFC')),
                ('ultimo_escaneo', models.DateTimeField(blank=True, null=True, verbose_name='Último Escaneo Registrado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('padre', models.ForeignKey(help_text='Usuario registrado con permisos exclusivos de edición para esta ficha.', on_delete=django.db.models.deletion.CASCADE, related_name='llaveros_nfc', to=settings.AUTH_USER_MODEL, verbose_name='Padre/Madre o Tutor')),
            ],
            options={
                'verbose_name': 'Llavero NFC',
                'verbose_name_plural': 'Llaveros NFC',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
